;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.LiftBrick",DevComment="")
+GameplayTagList=(Tag="Ability.NormalAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Push",DevComment="")
+GameplayTagList=(Tag="Camera.FirstPerson",DevComment="")
+GameplayTagList=(Tag="Camera.ThirdPerson",DevComment="")
+GameplayTagList=(Tag="Camera.TopDown",DevComment="")
+GameplayTagList=(Tag="Cooldown.LiftBrick",DevComment="")
+GameplayTagList=(Tag="Cooldown.NormalAttack",DevComment="")
+GameplayTagList=(Tag="Cooldown.Push",DevComment="")
+GameplayTagList=(Tag="Data.Cooldown",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Ability.LiftBrick",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Ability.LiftBrick.Place",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Ability.NormalAttack",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Ability.Push",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Ability.SpawnBrick",DevComment="")
+GameplayTagList=(Tag="State.Eliminated",DevComment="")
+GameplayTagList=(Tag="State.LiftBrickCarry",DevComment="")
+GameplayTagList=(Tag="State.SpawnBrickPreview",DevComment="")

